#!/bin/sh

INTERACTIVE=True
if [ -e /boot/firmware/config.txt ] ; then
  FIRMWARE=/firmware
else
  FIRMWARE=
fi

CMDLINE=/boot${FIRMWARE}/cmdline.txt
ASK_TO_REBOOT=0
RW_PART=""

calc_wt_size() {
    WT_HEIGHT=18
    WT_WIDTH=$(tput cols)

    if [ -z "$WT_WIDTH" ] || [ "$WT_WIDTH" -lt 60 ]; then
       WT_WIDTH=80
    fi
    if [ "$WT_WIDTH" -gt 178 ]; then
        WT_WIDTH=120
    fi
    WT_MENU_HEIGHT=$((WT_HEIGHT - 7))
}

do_finish() {
    if [ $ASK_TO_REBOOT -eq 1 ]; then
        whiptail --yesno "Would you like to reboot now?" 20 60 2
        if [ $? -eq 0 ]; then # yes
          sync
          reboot
        fi
    fi
    exit 0
}

get_bootro_now() {
  findmnt /boot${FIRMWARE} | grep -q " ro,"
  echo $?
}

get_rw_dev(){
    local run_dev=$(findmnt /boot${FIRMWARE} -o source -n | awk '{print substr($0, 1, length($0)-2)}')
    [ -e ${run_dev}p3 ] || return 2
    RW_PART=${run_dev}p3
    return 0
}

enable_bootro() {
    cat /etc/fstab | grep -q ".*/boot/firmware.*defaults "
    if [ $? -eq 0 ];then
        sed -i /etc/fstab -e "s#\(.*/boot$FIRMWARE.*\)defaults\(.*\)#\1defaults,ro\2#"
    fi
}

disable_bootro() {
    cat /etc/fstab | grep -q ".*/boot/firmware.*defaults,ro"
    if [ $? -eq 0 ];then
        sed -i /etc/fstab -e "s#\(.*/boot$FIRMWARE.*\)defaults,ro\(.*\)#\1defaults\2#"
    fi
}

do_overlayfs(){
    if [ "$INTERACTIVE" = True ]; then
        local value="ro"
        whiptail --yesno "Would you like to enable OverlayFS?" 20 60 2
        if [ $? -ne 0 ]; then # yes
            value="rw"
        fi
    else
        local value="$1"
    fi

    if [ $(get_bootro_now) -eq 0 ] ; then
        if ! mount -o remount,rw /boot${FIRMWARE} 2>/dev/null ; then
            echo "Unable to mount boot partition as writable - cannot disable"
            return 1
        fi
        BOOTRO=yes
    else
        BOOTRO=no
    fi

    get_rw_dev
    if [ $? -ne 0 ];then
        echo "Not found the writable partition."
        return 1
    fi

    sed -i $CMDLINE -e "s/\(^\| \)overlayroot=[^ ]*\( \|$\)/ /g; s/  \+/ /g; s/^ //; s/ $//"
    if [ "${value}" = "ro" ];then
        sed -i $CMDLINE -e "s|^|overlayroot=${RW_PART} |"
    elif [ "${value}" = "rw" ];then
        sed -i $CMDLINE -e "s|^|overlayroot=disabled |"
    fi
    if ! mount -o remount,ro /boot${FIRMWARE} 2>/dev/null ; then
        echo "Unable to remount boot partition as read-only"
    fi
    enable_bootro
    
    ASK_TO_REBOOT=1
}

do_bootrw(){
    if [ "$INTERACTIVE" = True ]; then
        local value="ro"
        whiptail --yesno "Would you like to set boot partition read-write temporarily?" 20 60 2
        if [ $? -eq 0 ]; then # yes
            value="rw"
        fi
    else
        local value="$1"
    fi
    if [ "${value}" = "rw" ];then
        if ! mount -o remount,rw /boot${FIRMWARE} 2>/dev/null ; then
            echo "Unable to mount boot partition as writable - cannot disable"
            return 1
        fi
    elif [ "${value}" = "ro" ];then
        if ! mount -o remount,ro /boot${FIRMWARE} 2>/dev/null ; then
            echo "Unable to remount boot partition as read-only"
        fi
    fi
}

do_factory_reset() {
    get_rw_dev
    if [ $? -ne 0 ];then
        echo "Not found the writable partition."
        return 1
    fi

    if [ "$INTERACTIVE" = True ]; then
        whiptail --yesno "This will disable OverlayFS and reset the third partition to factory settings. Continue?" 20 60 2
        if [ $? -ne 0 ]; then
            return 0
        fi
    fi

    if [ $(get_bootro_now) -eq 0 ] ; then
        if ! mount -o remount,rw /boot${FIRMWARE} 2>/dev/null ; then
            echo "Unable to mount boot partition as writable"
            return 1
        fi
    fi

    sed -i $CMDLINE -e "s/\(^\| \)overlayroot=[^ ]*\( \|$\)/ /g; s/  \+/ /g; s/^ //; s/ $//"
    sed -i $CMDLINE -e "s|^|overlayroot=disabled |"
    
    if ! mount -o remount,ro /boot${FIRMWARE} 2>/dev/null ; then
        echo "Unable to remount boot partition as read-only"
    fi

    TEMP_MOUNT=$(mktemp -d)
    if ! mount "$RW_PART" "$TEMP_MOUNT" 2>/dev/null; then
        echo "Failed to mount data partition"
        rmdir "$TEMP_MOUNT" 2>/dev/null
        return 1
    fi

    # Remove everything except lost+found and overlay
    find "$TEMP_MOUNT" -mindepth 1 -maxdepth 1 ! -name "lost+found" ! -name "overlay" -exec rm -rf {} + 2>/dev/null
    
    rm -rf "$TEMP_MOUNT"/overlay/* 2>/dev/null
    mkdir -p "$TEMP_MOUNT"/overlay/etc/systemd/system/systemd-remount-fs.service.d
    
    cat > "$TEMP_MOUNT"/overlay/etc/systemd/system/systemd-remount-fs.service.d/overlayroot.conf << 'EOF'
[Unit]
ConditionKernelCommandLine=!overlayroot=disabled
EOF
    
    if ! umount "$TEMP_MOUNT" 2>/dev/null; then
        echo "Failed to unmount data partition"
        return 1
    fi
    rmdir "$TEMP_MOUNT" 2>/dev/null
    
    ASK_TO_REBOOT=1
    
    if [ "$INTERACTIVE" = True ]; then
        whiptail --msgbox "Factory reset completed. OverlayFS disabled and partition restored to initial state." 20 60 2
    fi
}

do_expand_rootfs() {
    get_rw_dev
    if [ $? -ne 0 ];then
        echo "Not found the writable partition."
        return 1
    fi

    ROOT_PART=$RW_PART
    ROOT_DEV="/dev/$(lsblk -no pkname "$ROOT_PART")"

    PART_NUM="$(echo "$ROOT_PART" | grep -o "[[:digit:]]*$")"

    LAST_PART_NUM=$(parted "$ROOT_DEV" -ms unit s p | tail -n 1 | cut -f 1 -d:)
    if [ "$LAST_PART_NUM" -ne "$PART_NUM" ]; then
      whiptail --msgbox "$ROOT_PART is not the last partition. Don't know how to expand" 20 60 2
      return 0
    fi

    # Get the starting offset of the root partition
    PART_START=$(parted "$ROOT_DEV" -ms unit s p | grep "^${PART_NUM}" | cut -f 2 -d: | sed 's/[^0-9]//g')
    [ "$PART_START" ] || return 1
    # Return value will likely be error for fdisk as it fails to reload the
    # partition table because the root fs is mounted
    fdisk "$ROOT_DEV" <<EOF
p
d
$PART_NUM
n
p
$PART_NUM
$PART_START

p
w
EOF
    ASK_TO_REBOOT=1

    # now set up an init.d script
cat <<EOF > /etc/init.d/resize2fs_once &&
#!/bin/sh
### BEGIN INIT INFO
# Provides:          resize2fs_once
# Required-Start:
# Required-Stop:
# Default-Start: 3
# Default-Stop:
# Short-Description: Resize the root filesystem to fill partition
# Description:
### END INIT INFO

. /lib/lsb/init-functions

case "\$1" in
  start)
    log_daemon_msg "Starting resize2fs_once" &&
    resize2fs "$ROOT_PART" &&
    update-rc.d resize2fs_once remove &&
    rm /etc/init.d/resize2fs_once &&
    log_end_msg \$?
    ;;
  *)
    echo "Usage: \$0 start" >&2
    exit 3
    ;;
esac
EOF
    chmod +x /etc/init.d/resize2fs_once &&
    update-rc.d resize2fs_once defaults &&
    whiptail --msgbox "Root partition has been resized.\nThe filesystem will be enlarged upon the next reboot" 20 60 2
    ASK_TO_REBOOT=1
}


nonint() {
  "$@"
}

#
# Command line options for non-interactive use
#
for i in $*
do
  case $i in
  --expand-rootfs)
    do_expand_rootfs
    printf "Please reboot\n"
    exit 0
    ;;
  --factory-reset)
    do_factory_reset
    exit 0
    ;;
  nonint)
    INTERACTIVE=False
    #echo "$@"
    "$@"
    exit $?
    ;;
  *)
    # unknown option
    ;;
  esac
done

run(){
    calc_wt_size
    while true; do
        FUN=$(whiptail --title "EDATEC Software Configuration Tool (ed-overlay)" --backtitle "$(cat /proc/device-tree/model), ${FMEMSIZE}" --menu "Setup Options" $WT_HEIGHT $WT_WIDTH $WT_MENU_HEIGHT --cancel-button Finish --ok-button Select \
            "1 BOOT RW" "Temporarily remounting boot partition as read-write..." \
            "2 OVERLAYFS" "Configure OverlayFS" \
            "3 Expand Filesystem" "Ensures that all of the SD card is available" \
            "4 Factory Reset" "Reset third partition to factory settings" \
            3>&1 1>&2 2>&3)
        RET=$?
        if [ $RET -eq 1 ]; then
            do_finish
        elif [ $RET -eq 0 ]; then
            case "$FUN" in
                1\ *) do_bootrw ;;
                2\ *) do_overlayfs ;;
                3\ *) do_expand_rootfs ;;
                4\ *) do_factory_reset ;;
                *) whiptail --msgbox "Programmer error: unrecognized option" 20 60 1 ;;
            esac || whiptail --msgbox "There was an error running option $FUN" 20 60 1
        else
            exit 1
        fi
    done
}


if [ $(id -u) -ne 0 ]; then
  printf "Script must be run as root. Try 'sudo ed-config'\n"
  exit 1
fi
run